version: "3"
x-postgres-creds: &postgres-creds
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  db:
    image: postgres:14
    restart: always
    environment:
      <<: *postgres-creds
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      <<: *postgres-creds
      POSTGRES_HOST: db
    volumes:
      - ./src/relief_worker:/code/relief_worker
    ports:
      - 80:80
    depends_on:
      - db
